# Generated by Django 3.2.4 on 2024-09-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='ingredients',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='recipe_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
