# Generated by Django 3.2.4 on 2024-09-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cooking_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('professional', 'Professional')], default='beginner', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_food',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
