# Generated by Django 3.2.4 on 2024-09-11 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('category', models.CharField(choices=[('main_course', 'Main Course'), ('dessert', 'Dessert'), ('vegan', 'Vegan'), ('appetizer', 'Appetizer'), ('snack', 'Snack'), ('soup', 'Soup'), ('salad', 'Salad'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('side_dish', 'Side Dish'), ('beverage', 'Beverage'), ('gluten_free', 'Gluten Free'), ('low_carb', 'Low Carb'), ('high_protein', 'High Protein'), ('slow_cooker', 'Slow Cooker'), ('grill', 'Grill'), ('bake', 'Bake'), ('stir_fry', 'Stir Fry'), ('raw', 'Raw'), ('holiday', 'Holiday'), ('comfort_food', 'Comfort Food'), ('international', 'International'), ('quick_meal', 'Quick Meal'), ('meal_prep', 'Meal Prep')], default='main_course', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
